export const ledgerText = {
  title: "Practice exchange and PvP ledger",
  intro: "A cloud playtest: practice gold and items are separate from your kingdom. Trades never change your save.",
  signIn: "Sign in with Discord in Cloud, then refresh. Guest saves still work as usual.",
  refresh: "Refresh ledger",
  loading: "Working…",
  enroll: "Join practice exchange",
  grant: "Join once for 100 practice gold and 5 practice iron. These cannot be converted into kingdom resources.",
  balances: "Practice purse",
  gold: "gold",
  iron: "iron",
  banners: "banners",
  relics: "relics",
  item: "Practice item",
  quantity: "Quantity",
  price: "Total price in practice gold",
  list: "Put in escrow",
  listings: "Your open listings and latest 100",
  empty: "No listings yet.",
  buy: "Buy",
  cancel: "Cancel",
  priceFor: "for",
  seller: "Seller",
  status: { open: "Open", sold: "Sold", cancelled: "Cancelled", locked: "Snapshots locked" },
  pvp: "PvP challenge ledger",
  pvpHelp: "Unrated preparation only. Power is client-reported and unverified. Accepting locks a snapshot; combat, prizes, and ratings are not enabled.",
  saveHelp: "Both players must first push a save in Cloud. Power below is from your current army; the recorded save tick and hash are from your last upload.",
  yourId: "Your player ID",
  opponent: "Opponent Discord player ID (from their ledger)",
  power: "Reported power",
  challenge: "Send challenge",
  accept: "Accept and lock snapshot",
  noChallenges: "No challenges yet.",
  vs: "versus",
  tick: "save tick",
  done: "Recorded. Ledger refreshed.",
  refreshFailed: "Could not refresh. Check Cloud connection and Discord sign-in.",
  rejected: "Request declined. Refresh and check balances, ownership, and whether the record is already closed.",
  uncertain: "The response was interrupted. Retry this same request to learn whether it was recorded; you will not be charged twice.",
  retry: "Retry pending request",
  invalid: "Enter positive whole numbers up to 1,000,000,000.",
  invalidPower: "This practice stage supports whole-number power up to 1,000,000,000.",
  storage: "Browser storage is unavailable. The transaction was not sent.",
} as const;
